### ISSUE TITLE
error: ‘GROOVE_EVENT_DEVICEREOPENED’ was not declared in this scope

### ISSUE THREAD

**Issue by Fender-Bender-91** [andrewrk/node-groove#18]
Hi there I've run across the following error while node-gyp tries to build groove...

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@0.12.5 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '.../node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
../src/groove.cc: In function ‘void Initialize(v8::Handle<v8::Object>)’:
../src/groove.cc:86:51: error: ‘GROOVE_EVENT_DEVICEREOPENED’ was not declared in this scope
     SetProperty(exports, "_EVENT_DEVICEREOPENED", GROOVE_EVENT_DEVICEREOPENED);
                                                   ^
groove.target.mk:95: recipe for target 'Release/obj.target/groove/src/groove.o' failed
make: *** [Release/obj.target/groove/src/groove.o] Error 1
make: Leaving directory '.../node_modules/groove/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-21-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd .../node_modules/groove
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

**Comment by andrewrk** [comment]
I believe that the libgroove on your system is older than 4.3.0 and that's why you're getting this issue.

2 ways to solve this:

 * version-lock node-groove to 2.3.x (see https://github.com/andrewrk/node-groove#versions)
 * upgrade libgroove on your system to the newest release (currently 4.3.0)

The first way is probably easier for now. libgroove 4.3.0 was just released recently so package maintainers have not yet had a chance to get the newer version into your system.

**Comment by Fender-Bender-91** [comment]
Thanks it works now, I went with specifying groove 2.3.4 in my package.json file for now.
